const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const R=require('./dist/rental.js');
assert.equal(R.money(12000),'KSh 12,000');
assert.deepEqual(R.estimate({start:'2026-09-11',end:'2026-09-14',rate:12000,today:'2026-09-10'}),{days:3,subtotal:36000,discount:0,percent:0,total:36000});
assert.equal(R.estimate({start:'2026-09-11',end:'2026-09-14',endTime:'11:00',rate:3500,today:'2026-09-10'}).days,4);
assert.throws(()=>R.estimate({start:'2026-09-11',end:'2026-09-14',endTime:'09:00',rate:3500,today:'2026-09-10'}),/at least/);
assert.throws(()=>R.estimate({start:'2026-09-09',end:'2026-09-14',rate:3500,today:'2026-09-10'}),/today/);
assert.throws(()=>R.estimate({start:'2026-09-11',end:'2026-09-10',rate:3500,today:'2026-09-10'}),/after/);
assert.equal(R.estimate({start:'2026-09-11',end:'2026-10-11',rate:4000,offer:'longterm',today:'2026-09-10'}).total,84000);
assert.equal(R.estimate({start:'2026-09-11',end:'2026-09-14',rate:4000,offer:'weekend',today:'2026-09-10'}).total,9600);
for(const page of ['home','fleet']){const els=new Map();function el(id){if(!els.has(id))els.set(id,{value:'',innerHTML:'',textContent:'',dataset:{},classList:{toggle(){}},setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});return els.get(id)}const location={search:'',href:''};const context={Rental:R,URLSearchParams,location,document:{body:{dataset:{page}},getElementById:el,querySelector:el,querySelectorAll:()=>[],addEventListener(){}}};vm.createContext(context);vm.runInContext(fs.readFileSync('dist/app.js','utf8'),context);if(page==='fleet'){assert.equal((el('fleet-grid').innerHTML.match(/class="fleet-card"/g)||[]).length,19);vm.runInContext("category='Compact';renderFleet();",context);assert.equal((el('fleet-grid').innerHTML.match(/class="fleet-card"/g)||[]).length,2);vm.runInContext("reserve('tx')",context);el('quote-form').onsubmit({preventDefault(){}});assert.match(el('quote-result').innerHTML,/KSh 36,000/);}else{assert.equal((el('home-categories').innerHTML.match(/class="category-card"/g)||[]).length,5);assert.match(el('home-categories').innerHTML,/images\/2021tx.png/);assert.match(el('home-categories').innerHTML,/KSh 12,000/);assert.match(el('home-more').innerHTML,/WHY DRIVE WITH US/);el('pickup-time').value='10:00';el('dropoff-time').value='10:00';el('search-form').onsubmit({preventDefault(){}});assert.match(location.href,/fleet.html/);}}
const html=fs.readFileSync('dist/index.html','utf8')+fs.readFileSync('dist/fleet.html','utf8');for(const match of html.matchAll(/(?:src|href)="([^"?#]+)"/g)){const p=match[1];if(!p.includes(':'))assert.ok(fs.existsSync('dist/'+p),p);}
assert.ok(!/USD|DriveX|\$\d/.test(html+fs.readFileSync('dist/app.js','utf8')));
console.log('Passed: KSh formatting, rental durations and limits, offers, both page initializations, 19 fleet cards, 5 homepage categories, filtering, quote calculation, search navigation, local route references.');
