<?php
get_header();
if ( have_posts() ) : the_post();
	if ( driveflex_elementor_page() || trim( get_the_content() ) ) {
		the_content();
	} else {
		$fleet_url = home_url( '/fleet/' );
		$image = static fn( string $name ): string => get_theme_file_uri( 'assets/images/' . $name );
		?>
		<section class="df-hero" id="locations">
			<div class="df-container df-hero-copy"><h1>Drive Your Journey,<br><span>Your Way.</span></h1><p>Explore Kenya with comfort and style.<br>Your perfect rental. Your next adventure.</p><div class="df-perks"><div class="df-perk"><b>◇</b><span><strong>Clear Daily Rates</strong><small>Prices in Kenyan shillings</small></span></div><div class="df-perk"><b>♧</b><span><strong>Flexible Rentals</strong><small>For your kind of journey</small></span></div><div class="df-perk"><b>◷</b><span><strong>Easy Trip Planning</strong><small>Find your perfect ride</small></span></div></div></div>
			<div class="df-search-panel"><div class="df-search-tabs" aria-label="Rental type"><button type="button" class="is-active">♧ Rent a Car</button><button type="button">↗ One Way</button><button type="button">▦ Long Term</button></div><form class="df-search" action="<?php echo esc_url( $fleet_url ); ?>"><label>Pick-up Location<select name="location"><option>Nairobi City Centre</option><option>Jomo Kenyatta Airport</option><option>Wilson Airport</option><option>Mombasa</option></select></label><label>Pick-up Date<input type="date" name="pickup" required></label><label>Pick-up Time<input type="time" name="pickup_time" value="10:00" required></label><label>Drop-off Date<input type="date" name="dropoff" required></label><label>Drop-off Time<input type="time" name="dropoff_time" value="10:00" required></label><button class="df-button" type="submit">Search Cars</button></form></div>
		</section>
		<section class="df-section df-reveal"><div class="df-container"><div class="df-section-heading"><div><span class="df-eyebrow">CHOOSE YOUR RIDE</span><h2>Find the perfect car</h2></div><a class="df-button" href="<?php echo esc_url( $fleet_url ); ?>">View all cars →</a></div><div class="df-category-grid">
		<?php foreach ( array( array( 'Economy Cars', 'vitz.webp', 'KSh 3,500' ), array( 'Sedans', 'axio.webp', 'KSh 4,000' ), array( 'SUVs', '2021tx.webp', 'KSh 12,000' ), array( 'Luxury Cars', 'merc-c200.webp', 'KSh 15,000' ), array( 'Vans', 'hiace.webp', 'KSh 15,000' ) ) as $category ) : ?>
			<a class="df-category-card" href="<?php echo esc_url( $fleet_url ); ?>"><img src="<?php echo esc_url( $image( $category[1] ) ); ?>" alt="<?php echo esc_attr( $category[0] ); ?>" loading="lazy"><h3><?php echo esc_html( $category[0] ); ?></h3><p>Compare seats, doors and luggage</p><span>From <strong class="df-price"><?php echo esc_html( $category[2] ); ?></strong> / day</span></a>
		<?php endforeach; ?>
		</div></div></section>
		<section class="df-section df-reveal" id="deals"><div class="df-container df-promos"><article class="df-promo"><img src="<?php echo esc_url( $image( 'yellow-convertible.webp' ) ); ?>" alt="Toyota Prado TX"><div class="df-promo-copy"><small>Weekend Special</small><h2>Get <span>20% OFF</span></h2><p>A little more freedom for your next escape.</p><a class="df-button" href="<?php echo esc_url( $fleet_url ); ?>">Book now</a></div></article><article class="df-promo"><img src="<?php echo esc_url( $image( 'luxury-driver.webp' ) ); ?>" alt="Toyota Alphard with chauffeur"><div class="df-promo-copy"><small>Long Term Rentals</small><h2>Save up to <span>30%</span></h2><p>Settle in for business trips and extended stays of 30+ days.</p><a class="df-button" href="<?php echo esc_url( $fleet_url ); ?>">Learn more</a></div></article></div></section>
		<section class="df-section df-deals-section df-reveal"><div class="df-container"><div class="df-section-heading"><h2>Top Deals</h2><a class="df-outline-button" href="<?php echo esc_url( $fleet_url ); ?>">View all deals →</a></div><div class="df-deal-grid">
		<?php foreach ( array( array( 'Toyota Vitz', 'vitz.webp', 'KSh 3,500' ), array( 'Toyota Axio', 'axio.webp', 'KSh 4,000' ), array( 'Toyota Prado TX', '2021tx.webp', 'KSh 12,000' ), array( 'Mercedes C-200', 'merc-c200.webp', 'KSh 15,000' ), array( 'Toyota Harrier', 'harrier.webp', 'KSh 8,000' ) ) as $deal ) : ?>
			<a class="df-deal-card" href="<?php echo esc_url( $fleet_url ); ?>"><img src="<?php echo esc_url( $image( $deal[1] ) ); ?>" alt="<?php echo esc_attr( $deal[0] ); ?>" loading="lazy"><h3><?php echo esc_html( $deal[0] ); ?></h3><strong><?php echo esc_html( $deal[2] ); ?></strong><small> / day</small></a>
		<?php endforeach; ?>
		</div><p class="df-section-caption">Choose your dates to view the rental total for your journey.</p></div></section>
		<section class="df-section df-reveal" id="how-it-works"><div class="df-container"><div class="df-section-heading"><div><span class="df-eyebrow">SIMPLE BOOKING</span><h2>How it works</h2></div></div><div class="df-steps"><?php foreach ( array( array( '⌕', 'Search', 'Choose your location, dates and car.' ), array( '▦', 'Request', 'Review the estimate and send your details.' ), array( '♧', 'Confirm', 'We confirm availability before payment.' ), array( '⚿', 'Pick up', 'Collect your car at the agreed location.' ), array( '↶', 'Return', 'Return it at the agreed time.' ) ) as $step ) : ?><article class="df-step"><span><?php echo esc_html( $step[0] ); ?></span><div><h3><?php echo esc_html( $step[1] ); ?></h3><p><?php echo esc_html( $step[2] ); ?></p></div></article><?php endforeach; ?></div></div></section>
		<section class="df-section df-benefits-section df-reveal"><div class="df-container df-benefits-layout"><div><div class="df-section-heading"><h2>Why Drive With Us</h2></div><div class="df-benefit-grid"><?php foreach ( array( array( '01', 'Flexible travel', 'Choose a rental period that fits your plans.' ), array( '02', 'Kenya-wide journeys', 'Vehicles for city travel, airport pickups and road trips.' ), array( '03', 'Clear daily rates', 'Compare prices and specifications before you book.' ) ) as $benefit ) : ?><article class="df-benefit"><span><?php echo esc_html( $benefit[0] ); ?></span><p><?php echo esc_html( $benefit[2] ); ?></p><strong><?php echo esc_html( $benefit[1] ); ?></strong></article><?php endforeach; ?></div></div><aside class="df-mobile-callout"><img src="<?php echo esc_url( $image( 'driveflex-hero.webp' ) ); ?>" alt="DriveFlex rental car on the road" loading="lazy"><div><h2>Your next ride.<br>On the go.</h2><p>Browse, compare and plan your rental from any device.</p><a class="df-outline-button" href="<?php echo esc_url( $fleet_url ); ?>">Explore on mobile →</a></div></aside></div></section>
		<?php
	}
endif;
get_footer();
